version: '3.8'

services:

  mysql:
      image: mysql:8.0
      container_name: mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
        interval: 10s
        timeout: 5s
        retries: 10

  app:
    build: .
    container_name: client-service
    depends_on:
     mysql:
      condition: service_healthy
    ports:
      - "8091:8091"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
